language: android
jdk: oraclejdk7
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.gradle

android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - android-19
    - build-tools-19.1.0
    - sys-img-armeabi-v7a-android-19

# Emulator Management: Create, Start and Wait - taken from http://docs.travis-ci.com/user/languages/android/#How-to-Create-and-Start-an-Emulator
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
    - android list target
    - ./gradlew clean test --stacktrace # unit tests
    - ./gradlew assembleDebug
    # - ./gradlew build connectedAndroidTest #instrumentation tests
