package com.readtracker.android.support;

import android.content.res.ColorStateList;
import android.content.res.Resources;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.util.Log;
import android.widget.NumberPicker;

import com.readtracker.android.db.Book;

import java.lang.reflect.Field;

import androidx.appcompat.widget.AppCompatButton;
import androidx.core.view.ViewCompat;

/**
 * UI utilities for dealing with colors.
 */
public class ColorUtils {
  private static final String TAG = ColorUtils.class.getName();

  /**
   * Set the colors of divides on a NumberPicker.
   * <p>
   * Unfortunately Android API doesn't seem to offer a proper API for changing the color of
   * the dividers on the NumberPicker widget. After some Googling, it seems like the solution
   * below -- while super hacky -- is the common suggestion for solving this.
   * <p>
   * See https://stackoverflow.com/questions/24233556/changing-numberpicker-divider-color
   *
   * @param numberPicker NumberPicker instance to set colors for
   * @param color        The color to use for the NumberPicker dividers
   */
  static public void setNumberPickerDividerColorUsingHack(NumberPicker numberPicker, int color) {
    final String fieldToHack = "mSelectionDivider";
    final Field[] declaredFields = NumberPicker.class.getDeclaredFields();
    for(Field field : declaredFields) {
      if(field.getName().equals(fieldToHack)) {
        field.setAccessible(true);
        try {
          ColorDrawable colorDrawable = new ColorDrawable(color);
          field.set(numberPicker, colorDrawable);
        } catch(IllegalArgumentException | Resources.NotFoundException | IllegalAccessException e) {
          Log.e(TAG, Log.getStackTraceString(e));
        }
        break;
      }
    }
  }

  /**
   * Returns a color for the book instance.
   */
  public static int getColorForBook(Book book) {
    Integer storedColor = book.getColor();
    if(storedColor != null) {
      return storedColor;
    }
    // Fall back to autogenerated, fixed seed random color
    final String colorKey = book.getTitle() + book.getAuthor();
    float color = 360 * (Math.abs(colorKey.hashCode()) / (float) Integer.MAX_VALUE);
    return Color.HSVToColor(new float[]{color, 0.8f, 1.0f});
  }

  private static final int[][] ENABLED_DISABLED_STATE_DESCRIPTOR = new int[][]{
      new int[]{android.R.attr.state_enabled}, // enabled
      new int[]{-android.R.attr.state_enabled}, // disabled
  };

  public static void applyButtonColor(int color, AppCompatButton button) {
    final int disabledColor = androidx.core.graphics.ColorUtils.setAlphaComponent(color, 64);
    final double luminance = androidx.core.graphics.ColorUtils.calculateLuminance(color);
    int[] backgroundColors = new int[]{color, disabledColor};
    final ColorStateList backgroundColorStateList = new ColorStateList(ENABLED_DISABLED_STATE_DESCRIPTOR, backgroundColors);

    final int textColor = luminance < 0.4 ? Color.WHITE : Color.BLACK;
    final int disabledTextColor = androidx.core.graphics.ColorUtils.setAlphaComponent(textColor, 128);
    int[] textColors = new int[]{textColor, disabledTextColor};
    final ColorStateList textColorStateList = new ColorStateList(ENABLED_DISABLED_STATE_DESCRIPTOR, textColors);

    ViewCompat.setBackgroundTintList(button, backgroundColorStateList);
    button.setTextColor(textColorStateList);
  }
}
